services:
  postgres:
    image: postgres:15-alpine
    container_name: exhibition-postgres
    environment:
      POSTGRES_USER: craig-unix
      POSTGRES_PASSWORD: password
      POSTGRES_DB: exhibition_curator
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - exhibition-network
    restart: unless-stopped

  seed:
    image: node:18-alpine
    container_name: exhibition-seeder
    working_dir: /app
    volumes:
      - .:/app 
    environment:
      DATABASE_URL: postgres://craig-unix:password@postgres:5432/exhibition_curator
    depends_on:
      - postgres
    networks:
      - exhibition-network
    command: sh -c "npm install && sleep 10 && npm run seed"

networks:
  exhibition-network:
    external: true

volumes:
  postgres_data:
